// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
//
// This app's Analytics page reads via the custom /api/charts route
// (server/routes/charts.ts) with locally-typed rows, not AppKit's
// useAnalyticsQuery/queryKey path — so the QueryRegistry is intentionally
// empty. Regenerate if you adopt the queryKey mechanism for a query.
import "@databricks/appkit-ui/react";

declare module "@databricks/appkit-ui/react" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface QueryRegistry {}
}
